# ============================================================================
# Script Name:    cloud_init_permissions.yaml
# Author:         Mauro García
# Version:        1.0
# Description:    This Playbook configures netplan when creating a new server
#                 in IONOS Cloud Environment
# Repository:     https://github.com/magarpol/ansible
# Last Updated:   2025-01-30
# ============================================================================
#cloud-config
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
       version: 2
       ethernets:
         ens6: 
            addresses:
              - #IP_ADDRESS#/23
            gateway4: #GATEWAY#
            nameservers:
              addresses:
                - #DNS1#
                - #DNS2#

runcmd:
  - netplan apply
