---
- name: Install and enable journalctl on Debian 12 servers
  hosts: all
  become: yes

  tasks: 
    - name: Check if OS is Debian 12
      ansible.builtin.shell: cat /etc/os-release | grep '^ID' | cut -d'=' -f2
      register: os_id
      changed_when: false
      check_mode: no
  
    - name: Install journalctl if not installed
      ansible.builtin.package:
        name: systemd
        state: present
      when: os_id.stdout == "debian" and os_id.stdout == "debian" and ansible_distributions_version('12', '==')

    - name: Enable journalctl service
      ansible.builtin.service:
        name: systemd-journald
        started: yes
        enabled: yes
      when: os_id.stdout == "debian" and os_id.stdout == "debian" and ansible_distributions_version('12', '==')

    - name: Stop and disable rsyslog service if journalctl is enabled
      ansible.builtin.service:
        name: rsyslog
        state: stopped
        enabled: no
      when: os_id.stdout == "debian" and os_id.stdout == "debian" and ansible_distributions_version('12', '!=')
