# ============================================================================
# Script Name:    logwatch.yaml
# Author:         Mauro García
# Version:        1.0
# Description:    This Playbook installs and configures Logwatch on servers
# Repository:     https://github.com/magarpol/scripts
# Last Updated:   2025-01-30
# ============================================================================
---
- name: Configure Logwatch on all hosts
  hosts: all
  become: yes

  vars:
    source_dir: /tmp
    plugin_dir: /usr/lib/check_mk_agent/plugins
    logwatch_dir: /etc/check_mk/

  tasks:
    - name: Copy mk_logwatch.py to plugin directory
      ansible.builtin.copy:
        src: "{{ source_dir }}/mk_logwatch.py"
        dest: "{{ plugin_dir }}/mk_logwatch.py"
        mode: '0755'

    - name: Copy logwatch.cfg to logwatch directory
      ansible.builtin.copy:
        src: "{{ source_dir }}/logwatch.cfg"
        dest: "{{ logwatch_dir }}/logwatch.cfg"
        mode: '0644'
        
    - name: Configure logwatch.cfg
      ansible.builtin.blockinfile:
        path: "{{ logwatch_dir }}/logwatch.cfg"
        block: 
          /var/log/unattended-upgrades/unattended-upgrades.log
            C error
            C fail
      
    - name: Execute mk_logwatch.py
      ansible.builtin.command:
        cmd: "python3 {{ plugin_dir }}/mk_logwatch.py"

    - name: Restart check_mk_agent.socket
      ansible.builtin.systemd:
        name: check_mk_agent.socket
        state: restarted
