---
- name: Install mailutils and Postfix
  hosts: server1, server2, server3
  become: yes

  pre_tasks:
    - name: Preconfigure Postfix with "Internet Site"
      debconf:
        name: postfix
        question: "postfix/main_mailer_type"
        value: "Internet Site"
        vtype: string
        
    - name: Set name dynamically to each server hostname
      debconf:
        name: postfix
        question: "postfix/mailname"
        value: "{{ inventory_hostname }}"
        vtype: string
  
  tasks: 
    - name: Install mailutils 
      apt:
        name: mailutils 
        state: present
        
    - name: Install Postfix
      systemd:
        name: postfix
        state: present
  
  
    
