---
- name: Install mailutils and Postfix
  hosts: [linux_servers]
  become: yes
  
  tasks: 
    - name: Install mailutils and postfix
      apt:
        name:
          - mailutils
          - postfix
        state: present
      debconf:
        name: postfix
        question: postfix/mailname
        value: "Internet Site"
        vtype: string
        
    - name: Postfix service is enabled and started
      systemd:
        name: postfix
        enabled: yes
        state: started
  
  
    
