---
- name: Configure unattended-upgrades 
  hosts: all
  become: yes

  tasks:
    - name: Ensure unattended-upgrades is installed
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Enable unattended-upgrades service
      ansible.builtin.systemd:
        name: unattended-upgrades.service
        enabled: yes
        state: started

    - name: Ensure Debian stable Allowed-Origin is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//      "o=Debian,a=stable";'
        line: '      "o=Debian,a=stable";'
        state: present

    - name: Ensure Debian stable-updates Allowed-Origin is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//      "o=Debian,a=stable-updates";'
        line: '      "o=Debian,a=stable-updates";'
        state: present
              
    - name: Add more allowed origins block 
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        marker: "# {mark} MORE ALLOWED ORIGINS"
        insertafter: '^      "o=Debian,a=stable-updates";$'
        block: |
                  "origin=Debian,codename=${distro_codename}-stable-security,label=Debian-Security";
                  "origin=Docker,codename=${distro_codename},label=Docker CE";
                  "o=Docker,a=bookworm,l=Docker CE,c=stable";

    - name: Ensure Unattended-Upgrade::Mail is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//?\s*Unattended-Upgrade::Mail'
        line: 'Unattended-Upgrade::Mail "servicedesk@mid.de";' 
        state: present

    - name: Ensure Unattended-Upgrade::Automatic-Reboot is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//?\s*Unattended-Upgrade::Automatic-Reboot'
        line: 'Unattended-Upgrade::Automatic-Reboot "true";'
        state: present

    - name: Ensure Unattended-Upgrade::Automatic-Reboot-Time is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//?\s*Unattended-Upgrade::Automatic-Reboot-Time'
        line: 'Unattended-Upgrade::Automatic-Reboot-Time "03:00";'
        state: present

    - name: Ensure Unattended-Upgrade::Verbose is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//?\s*Unattended-Upgrade::Verbose'
        line: 'Unattended-Upgrade::Verbose "true";'
        state: present

    - name: Restart unattended-upgrades
      ansible.builtin.systemd:
        name: unattended-upgrades.service
        state: restarted
