---
- name: Check and fix xz-utils
  hosts: all
  become: yes
  tasks:

    - name: Check if xz-utils is installed
      ansible.builtin.command: dpkg-query -W -f='{Version}' xz-utils
      register: xz_utils_version
      failed_when: xz_utils_version.rc != 0
      ignore_errors: yes

    - name: Determine if xz-utils is vulnerable
      ansible.builtin.set_fact:
        is_vulnerable: "{{ xz_utils_version.stdout is defined and xz_utils_version.stdout < '5.2.12' }}"
      when: xz_utils_version.stdout is defined

    - name: Update xz-utils if it is vulnerable
      ansible.builtin.apt:
        name: xz-utils
        state: latest
      when: is_vulnerable | default(false)

    - name: Notify about xz-utils status
      ansible.builtin.debug:
        msg: >-
          {% if xz_utils_version.rc != 0 %}
            xz-utils is not installed on this host.
          {% elif is_vulnerable %}
            Vulnerable version of xz-utils found and updated to the latest version.
          {% else %}
            xz-utils is already up to date or not vulnerable.
          {% endif %}

